// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcV_gW_88emq3ycdWjZ9lv9iD9ZUZXy-4',
    appId: '1:871676728917:web:4e55f01f7fd7980382e6dc',
    messagingSenderId: '871676728917',
    projectId: 'unity-eats-216bf',
    authDomain: 'unity-eats-216bf.firebaseapp.com',
    storageBucket: 'unity-eats-216bf.appspot.com',
    measurementId: 'G-DDJ8KGN64Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf9mpjZphiYHgOe_IjBOJgOUKbit7Dg2Q',
    appId: '1:871676728917:android:485cb01300f4895c82e6dc',
    messagingSenderId: '871676728917',
    projectId: 'unity-eats-216bf',
    storageBucket: 'unity-eats-216bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV10G6_g_5PQVn8kWTyX2L_FUZkSMBCFY',
    appId: '1:871676728917:ios:8a02b17b0adfac1b82e6dc',
    messagingSenderId: '871676728917',
    projectId: 'unity-eats-216bf',
    storageBucket: 'unity-eats-216bf.appspot.com',
    iosClientId: '871676728917-ft6i4rhvtuv8htsplusrg6o3h9o4lt7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.unityEats',
  );
}
